version: '3.8'

services:
  memory:
    image: mcp/memory
    container_name: gmini-memory
    volumes:
      - ./data/memory:/data
    ports:
      - "3000:3000"
    environment:
      - MCP_SERVER_PORT=3000

  playwright:
    image: mcp/playwright
    container_name: gmini-playwright
    ports:
      - "3001:3000"
    environment:
      - MCP_SERVER_PORT=3000
    cap_add:
      - SYS_ADMIN
    
  node-sandbox:
    image: mcp/node-code-sandbox
    container_name: gmini-node-sandbox
    ports:
      - "3002:3000"
    environment:
      - MCP_SERVER_PORT=3000
    volumes:
      - ./data/node-sandbox:/app/files
      
  proxy:
    build:
      context: .
      dockerfile: docker/proxy.Dockerfile
    container_name: gmini-proxy
    ports:
      - "8080:8080"
    environment:
      - MEMORY_URL=http://memory:3000
      - PLAYWRIGHT_URL=http://playwright:3000
      - NODE_SANDBOX_URL=http://node-sandbox:3000
    depends_on:
      - memory
      - playwright
      - node-sandbox