# Docker Offload Configuration

# Cloud Provider Settings
provider:
  auto_select: true  # Automatically select the best available provider
  preferences:
    - provider: aws
      region: auto
    - provider: gcp
      region: auto
    - provider: azure
      region: auto

# Resource Allocation
resources:
  gpu:
    min_memory: 16G
    type: ["NVIDIA-A100", "NVIDIA-V100", "NVIDIA-T4"]
    count: 1
  cpu:
    min_cores: 8
    memory: 32G

# Network Configuration
network:
  bandwidth: "10Gbps"
  latency_threshold: "50ms"

# Security
security:
  encrypted_traffic: true
  key_rotation: 24h

# Cost Management
costs:
  max_hourly_rate: 5.00  # USD
  auto_shutdown: true
  idle_timeout: 15m

# Performance
performance:
  auto_scaling: true
  min_instances: 1
  max_instances: 3

# Monitoring
monitoring:
  metrics_enabled: true
  logging_level: info
  alert_threshold:
    cpu_utilization: 90
    gpu_utilization: 85
    memory_usage: 90